package api_schema

import (
	"net"
	"time"

	"github.com/akitasoftware/akita-libs/akid"
	"github.com/akitasoftware/akita-libs/spec_summary"
	"github.com/akitasoftware/akita-libs/tags"
)

// NetworkDirection is always relative to subject service.
type NetworkDirection string

const (
	Inbound  NetworkDirection = "INBOUND"
	Outbound NetworkDirection = "OUTBOUND"
)

type APISpecState string

const (
	APISpecInitialized APISpecState = "INITIALIZED"
	APISpecComputing   APISpecState = "COMPUTING"
	APISpecDone        APISpecState = "DONE"
	APISpecError       APISpecState = "ERROR"
)

// References an API spec by ID or version. Only one field may be set.
type APISpecReference struct {
	ID      *akid.APISpecID `json:"id,omitempty"`
	Version *string         `json:"version,omitempty"`
}

// Also used as a model in specs_db.
type APISpecVersion struct {
	tableName struct{} `pg:"api_spec_versions" json:"-"`

	Name         string         `pg:"name" json:"name"`
	APISpecID    akid.APISpecID `pg:"api_spec_id" json:"api_spec_id"`
	ServiceID    akid.ServiceID `pg:"service_id" json:"service_id"`
	CreationTime time.Time      `pg:"creation_time" json:"creation_time"`
}

type CheckpointRequest struct {
	// Optional: name to assign to the API spec generated by the checkpoint.
	APISpecName string `json:"api_spec_name"`
}

type CheckpointResponse struct {
	APISpecID akid.APISpecID `json:"api_spec_id"`
}

type CreateLearnSessionRequest struct {
	// Optional argument that specifies an existing API spec that specs generated
	// from this learn session should extend upon.
	BaseAPISpecRef *APISpecReference `json:"base_api_spec_ref,omitempty"`

	// Optional key-value pairs to tag this learn session.
	// We reserve tags with "x-akita-" prefix for internal use.
	Tags map[tags.Key]string `json:"tags,omitempty"`

	// Optional name for the learn session.
	Name string `json:"name"`
}

type LearnSession struct {
	ID           akid.LearnSessionID `json:"id"`
	Name         string              `json:"name"`
	IdentityID   akid.IdentityID     `json:"identity_id"`
	ServiceID    akid.ServiceID      `json:"service_id"`
	CreationTime time.Time           `json:"creation_time"`

	// Optional field whose presence indicates that the learn session is an
	// extension to an existing API spec.
	BaseAPISpecID *akid.APISpecID `json:"base_api_spec_id,omitempty"`

	// HasMany relationship.
	Tags []LearnSessionTag `json:"tags"`
}

func NewLearnSession(
	ID akid.LearnSessionID,
	Name string,
	IdentityID akid.IdentityID,
	ServiceID akid.ServiceID,
	CreationTime time.Time,

	BaseAPISpecID *akid.APISpecID,

	Tags []LearnSessionTag,
) *LearnSession {
	return &LearnSession{
		ID:           ID,
		Name:         Name,
		IdentityID:   IdentityID,
		ServiceID:    ServiceID,
		CreationTime: CreationTime,

		BaseAPISpecID: BaseAPISpecID,

		Tags: Tags,
	}
}

// An extended version of LearnSession that includes extra information for
// presentation in the web console when listing learn sessions.
// XXX Should inherit from LearnSession, but Go. :(
type ListedLearnSession struct {
	ID           akid.LearnSessionID `json:"id"`
	Name         string              `json:"name"`
	IdentityID   akid.IdentityID     `json:"identity_id"`
	ServiceID    akid.ServiceID      `json:"service_id"`
	CreationTime time.Time           `json:"creation_time"`

	// Optional field whose presence indicates that the learn session is an
	// extension to an existing API spec.
	BaseAPISpecID *akid.APISpecID `json:"base_api_spec_id,omitempty"`

	// HasMany relationship.
	Tags []LearnSessionTag `json:"tags"`

	// Identifies the set of API specs that are derived from this learn session.
	APISpecs []akid.APISpecID `json:"api_spec_ids"`

	Stats *LearnSessionStats `json:"stats,omitempty"`
}

func NewListedLearnSession(
	ID akid.LearnSessionID,
	Name string,
	IdentityID akid.IdentityID,
	ServiceID akid.ServiceID,
	CreationTime time.Time,

	BaseAPISpecID *akid.APISpecID,

	Tags []LearnSessionTag,
	APISpecs []akid.APISpecID,
	Stats *LearnSessionStats,
) *ListedLearnSession {
	return &ListedLearnSession{
		ID:           ID,
		Name:         Name,
		IdentityID:   IdentityID,
		ServiceID:    ServiceID,
		CreationTime: CreationTime,

		BaseAPISpecID: BaseAPISpecID,

		Tags:     Tags,
		APISpecs: APISpecs,
		Stats:    Stats,
	}
}

// Statistics about a single learn session.
type LearnSessionStats struct {
	// The number of witnesses in this learn session.
	NumWitnesses int `json:"num_witnesses"`
}

func NewLearnSessionStats(NumWitnesses int) *LearnSessionStats {
	return &LearnSessionStats{
		NumWitnesses: NumWitnesses,
	}
}

type LearnSessionTag struct {
	tableName struct{} `pg:"learn_session_tags"`

	LearnSessionID akid.LearnSessionID `pg:"learn_session_id" json:"learn_session_id"`
	Key            tags.Key            `pg:"key" json:"key"`
	Value          string              `pg:"value,use_zero" json:"value"`
}

type CreateSpecRequest struct {
	// Learn sessions to create spec from.
	LearnSessionIDs []akid.LearnSessionID `json:"learn_session_ids"`

	// Optional: name to assign to the API spec generated by the checkpoint.
	Name string `json:"name"`

	// Optional: user-specified tags.
	Tags map[tags.Key]string `json:"tags"`
}

type UploadSpecRequest struct {
	Name string              `json:"name"`
	Tags map[tags.Key]string `json:"tags,omitempty"`

	// TODO(kku): use multipart/form-data upload once we can support it.
	Content string `json:"content"`
}

type UploadSpecResponse struct {
	ID akid.APISpecID `json:"id"`
}

type ListSessionsResponse struct {
	Sessions []*ListedLearnSession `json:"sessions"`
}

type UploadWitnessesRequest struct {
	ClientID akid.ClientID    `json:"client_id"`
	Reports  []*WitnessReport `json:"reports"`
}

type WitnessReport struct {
	Direction       NetworkDirection `json:"direction"`
	OriginAddr      net.IP           `json:"origin_addr"`
	OriginPort      uint16           `json:"origin_port"`
	DestinationAddr net.IP           `json:"destination_addr"`
	DestinationPort uint16           `json:"destination_port"`

	ClientWitnessTime time.Time `json:"client_witness_time"`

	// A serialized Witness protobuf in base64 URL encoded format.
	WitnessProto string `json:"witness_proto"`

	ID   akid.WitnessID      `json:"id"`
	Tags map[tags.Key]string `json:"tags"`

	// Hash of the witness proto. Only used internally in the client.
	Hash string `json:"-"`
}

type CreateSpecResponse struct {
	ID akid.APISpecID `json:"id"`
}

type GetSpecMetadataResponse struct {
	// TODO: remove
	// If the spec was created from a learn session, the session's ID is included.
	LearnSessionID *akid.LearnSessionID `json:"learn_session_id,omitempty"`

	// If the spec was created from a learn session, the session's ID is included.
	// If the spec was created by merging other API specs, those spec's session
	// IDs are included.
	LearnSessionIDs []akid.LearnSessionID `json:"learn_session_ids,omitempty"`

	Name string `json:"name"`

	State APISpecState `json:"state"`

	Tags map[tags.Key]string `json:"tags"`
}

type GetSpecResponse struct {
	Content string `json:"content"`

	// TODO: remove
	// If the spec was created from a learn session, the session's ID is included.
	LearnSessionID *akid.LearnSessionID `json:"learn_session_id,omitempty"`

	// If the spec was created from a learn session, the session's ID is included.
	// If the spec was created by merging other API specs, those spec's session
	// IDs are included.
	LearnSessionIDs []akid.LearnSessionID `json:"learn_session_ids,omitempty"`

	Name string `json:"name"`

	State APISpecState `json:"state"`

	Summary *spec_summary.Summary `json:"summary,omitempty"`

	Tags map[tags.Key]string `json:"tags"`
}

type SetSpecVersionRequest struct {
	APISpecID akid.APISpecID `json:"api_spec_id"`
}

// Types used in spec list
type SpecInfo struct {
	ID akid.APISpecID `json:"id"`

	Name string `json:"name,omitempty"`

	// Whether the spec was LEARNED or LEARNED_WITH_EDITS.
	CreationMode string `json:"creation_mode"`

	// If the spec was created from a learn session, the session's ID is included.
	// Deprecated: use learn_session_ids instead.
	LearnSessionID *akid.LearnSessionID `json:"learn_session_id,omitempty"`

	LearnSessionIDs []akid.LearnSessionID `json:"learn_session_ids,omitempty"`

	// Deprecated: for old specs, tags are inherited from learn sessions.
	// Use Tags field instead.
	LearnSessionTags []LearnSessionTag `json:"learn_session_tags,omitempty"`

	Tags        map[tags.Key]string `json:"tags,omitempty"`
	VersionTags []string            `json:"version_tags,omitempty"`

	CreationTime time.Time    `json:"creation_time"`
	EditTime     time.Time    `json:"edit_time"`
	State        APISpecState `json:"state"`

	PRStatus string `json:"pr_status,omitempty"`

	// Model and trace statistics
	// Number of endpoints, number of witnesses incorporated into model, and
	// raw number of witnesses used as input.
	NumEndpoints    int `json:"num_endpoints,omitempty"`
	NumEvents       int `json:"num_events,omitempty"`
	NumStoredEvents int `json:"num_stored_events,omitempty"`

	// Deployment times
	TraceStartTime *time.Time `json:"trace_start_time,omitempty"`
	TraceEndTime   *time.Time `json:"trace_end_time,omitempty"`
}

type ListSpecsResponse struct {
	Specs []SpecInfo `json:"specs"`
}
